/* Generated By:JavaCC: Do not edit this line. PiaCompillerConstants.java */
package compilador;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PiaCompillerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INICIAPROG = 5;
  /** RegularExpression Id. */
  int ABREBLOCO = 6;
  /** RegularExpression Id. */
  int FECHABLOCO = 7;
  /** RegularExpression Id. */
  int FIMINSTRUCAO = 8;
  /** RegularExpression Id. */
  int TIPOINT = 9;
  /** RegularExpression Id. */
  int TIPOFLOAT = 10;
  /** RegularExpression Id. */
  int TIPOBOL = 11;
  /** RegularExpression Id. */
  int IF = 12;
  /** RegularExpression Id. */
  int ABREPAR = 13;
  /** RegularExpression Id. */
  int FECHAPAR = 14;
  /** RegularExpression Id. */
  int OPREL = 15;
  /** RegularExpression Id. */
  int OPBOOL = 16;
  /** RegularExpression Id. */
  int WHILE = 17;
  /** RegularExpression Id. */
  int DO = 18;
  /** RegularExpression Id. */
  int ASSIGN = 19;
  /** RegularExpression Id. */
  int PLUS = 20;
  /** RegularExpression Id. */
  int MINUS = 21;
  /** RegularExpression Id. */
  int MULT = 22;
  /** RegularExpression Id. */
  int DIV = 23;
  /** RegularExpression Id. */
  int CONSTANT = 24;
  /** RegularExpression Id. */
  int DIGITO = 25;
  /** RegularExpression Id. */
  int ID = 26;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"bah_piazada\"",
    "\"abre_jaguara\"",
    "\"fecha_jaguara\"",
    "\"cabo_o_fandango\"",
    "\"torresmo\"",
    "\"cuca\"",
    "\"chimarrao\"",
    "\"eh_memo\"",
    "\"(\"",
    "\")\"",
    "<OPREL>",
    "<OPBOOL>",
    "\"enquanto_piazada\"",
    "\"faz_piazada\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<CONSTANT>",
    "<DIGITO>",
    "<ID>",
  };

}
